name: Python Code Quality
on:
  - push
  - workflow_dispatch
jobs:
  pylint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: "Install requirements"
        run: pip3 install -r requirements.txt

      - name: "Lint Python Files"
        run: pylint **/*.py --fail-under=9