name: Run Pytest with Coverage Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-cov

      - name: Run Pytest with Coverage Check
        run: |
          if python -m pytest --collect-only | grep -q "collected 0 items"; then
            echo "No tests collected, skipping coverage check."
          else
            python -m pytest --cov=./ --cov-fail-under=80 --cov-omit='*test*'
          fi




